# Generated by Django 2.2.6 on 2019-10-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('share_id', models.CharField(max_length=10)),
                ('share_data', models.TextField()),
            ],
        ),
    ]
