# Generated by Django 2.2.6 on 2019-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fingerprint',
            field=models.TextField(default=''),
        ),
    ]
