# Generated by Django 2.2.6 on 2019-11-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coordinates',
            field=models.CharField(default='', max_length=100),
        ),
    ]
